const SUPABASE_URL='https://cvsvlnrikkocolipunru.supabase.co';
const SUPABASE_KEY='sb_publishable_hlhh8l5Qk9HzubKN0QPVHg_QZHByQ-m';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const WA='917981977002';const $=s=>document.querySelector(s);const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString('so-SO',{day:'2-digit',month:'short',year:'numeric'});
let user,enroll,attendance=[];
function msg(t,ok=false){const m=$('#dashMsg');m.textContent=t;m.className='message show '+(ok?'success':'error');setTimeout(()=>m.className='message',3500)}
async function init(){const {data:{user:u}}=await supabaseClient.auth.getUser();user=u;if(!user){location.href='login.html';return}$('#userEmail').textContent=user.email||'';const {data:p}=await supabaseClient.from('profiles').select('*').eq('id',user.id).maybeSingle();$('#userName').textContent=p?.full_name||'Isticmaale';const {data:es,error}=await supabaseClient.from('ruqyah_enrollments').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(error){msg(error.message);return}enroll=es?.[0];if(!enroll){$('#noPlan').style.display='block';return}$('#noPlan').style.display='none';$('#planText').textContent=`${enroll.plan_days} maalmood`;$('#startText').textContent=fmt(enroll.start_date);$('#timeText').textContent=String(enroll.preferred_time).slice(0,5);$('#waDash').href=`https://wa.me/${WA}?text=${encodeURIComponent('Asalaamu calaykum DARU-SHIFA, waxaan rabaa caawimaad ku saabsan Ruqyada Quraanka. Magacaygu waa '+(p?.full_name||'')+'.')}`;const {data:a,error:ae}=await supabaseClient.from('attendance').select('*').eq('enrollment_id',enroll.id).order('attendance_date',{ascending:true});if(ae){msg(ae.message);return}attendance=a||[];render();}
function render(){const start=new Date(enroll.start_date+'T00:00:00'),today=new Date();today.setHours(0,0,0,0);const current=Math.max(1,Math.min(enroll.plan_days,Math.floor((today-start)/86400000)+1));$('#dayNo').textContent=current;const present=attendance.filter(x=>x.status==='present').length,missed=attendance.filter(x=>x.status==='missed').length;$('#present').textContent=present;$('#missed').textContent=missed;$('#remaining').textContent=Math.max(enroll.plan_days-present-missed,0);$('#progress').textContent=Math.round(present/enroll.plan_days*100)+'%';$('#todayDate').textContent=fmt(new Date().toISOString().slice(0,10));const map=new Map(attendance.map(x=>[x.attendance_date,x.status]));const todayKey=new Date().toISOString().slice(0,10);const existing=map.get(todayKey);$('#presentBtn').disabled=!!existing;$('#missedBtn').disabled=!!existing;$('#presentBtn').onclick=()=>save('present');$('#missedBtn').onclick=()=>save('missed');if(existing)msg('Maanta hore ayaa loo calaamadeeyey: '+(existing==='present'?'XAADIR':'MAQNAANSHO'),true);const startDate=new Date(enroll.start_date+'T00:00:00');let html='';for(let i=0;i<enroll.plan_days;i++){const d=new Date(startDate);d.setDate(d.getDate()+i);const key=d.toISOString().slice(0,10),s=map.get(key);html+=`<tr><td>Maalin ${i+1}</td><td>${fmt(key)}</td><td>${s?`<span class="status ${s}">${s==='present'?'XAADIR':'MAQNAANSHO'}</span>`:'<span class="muted">Wali lama calaamadin</span>'}</td></tr>`}$('#attBody').innerHTML=html;}
async function save(status){const key=new Date().toISOString().slice(0,10);const {error}=await supabaseClient.from('attendance').upsert({enrollment_id:enroll.id,user_id:user.id,attendance_date:key,status},{onConflict:'enrollment_id,attendance_date'});if(error){msg(error.message);return}msg(status==='present'?'Maanta waxaad calaamadisay XAADIR.':'Maanta waxaad calaamadisay MAQNAANSHO.',true);const {data:a}=await supabaseClient.from('attendance').select('*').eq('enrollment_id',enroll.id);attendance=a||[];render();}
$('#logout')?.addEventListener('click',async()=>{await supabaseClient.auth.signOut();location.href='index.html'});init();
